// constants.js
window.MyGovData = {
  reportDate: '02nd April 2025',
  primeMinisterName: 'Narendra Modi',
  launchDate: '26 July 2014',
  registeredUsers: '5.34 Crore +',
  userCount2023: '3,05,04,557',
  userCount2025: '5,34,03,320',
  increaseInCount: '2,28,98,763',
  growthPercent: '75.07',
  doTaskCount: 1736,
  doTaskSubmissions: '16.89+ Lakh',
  discussCount: 1020,
  discussSubmissions: '55.64+ Lakh',
  quizCount: 1201,
  quizSubmissions: '287.53+ Lakh',
  pollCount: 323,
  pollSubmissions: '37.58+ Lakh',
  pledgeCount: 138,
  pledgeSubmissions: '234.71+ Lakh',
  stateInstancesList: 'Himachal Pradesh, Haryana, Maharashtra, Madhya Pradesh, Arunachal Pradesh, Assam, Manipur, Tripura, Chhattisgarh, Jharkhand, Nagaland, Uttarakhand, Goa, Tamil Nadu, Uttar Pradesh, Mizoram, Rajasthan, Jammu & Kashmir, Ladakh, Karnataka, Gujarat, Dadra and Nagar Haveli and Daman and Diu, Andaman and Nicobar Islands, Chandigarh',
  whatsappFollowers: '7.37+ lakh',
  facebookFollowers: '15.14+ lakh',
  twitterFollowers: '33.11+ lakh',
  instagramFollowers: '30.73+ lakh',
  telegramFollowers: '6.19+ lakh',
  youtubeFollowers: '7.43+ lakh',
  linkedinFollowers: '1.63+ lakh',
  pinterestFollowers: '19.80K+',
  roposoFollowers: '14.47L+',
  chingariFollowers: '4.90L+',
  sharechatFollowers: '82.22K+',
  localizationLanguages: 'Hindi, Assamese, Gujarati, Punjabi, Marathi, Bangla, Telugu, Tamil, Kannada, Malayalam, Odia',
  socialMediaLanguages: 'Hindi, Sanskrit, Assamese, Gujarati, Punjabi, Marathi, Bangla, Telugu, Tamil, Kannada, Malayalam, Odia'
};
